
export const location = {
  '': [],
  'Andhra Pradesh': [],
  'Arunachal Pradesh': [],
  'Assam': [],
  'Bihar': [],
  'Chhattisgarh': [],
  'Goa': [],
  'Gujarat': [],
  'Haryana': [],
  'Himachal Pradesh': [],
  'Jammu and Kashmir': [],
  'Jharkhand': [],
  'Karnataka': [
    '',
    'Bagalkot',
    'Ballari (Bellary)',
    'Belagavi (Belgaum)',
    'Bengaluru (Bangalore) Rural',
    'Bengaluru (Bangalore) Urban',
    'Bidar',
    'Chamarajanagar',
    'Chikkaballapur',
    'Chikkamagaluru (Chikmagalur)',
    'Chitradurga',
    'Dakshina Kannada',
    'Davanagere',
    'Dharwad',
    'Gadag',
    'Hassan',
    'Haveri',
    'Kalaburagi (Gulbarga)',
    'Kodagu',
    'Kolar',
    'Koppal',
    'Mandya',
    'Mysuru (Mysore)',
    'Raichur',
    'Ramanagara',
    'Shivamogga (Shimoga)',
    'Tumakuru (Tumkur)',
    'Udupi',
    'Uttara Kannada (Karwar)',
    'Vijayapura (Bijapur)',
    'Yadgir',
  ],
  'Kerala': [],
  'Madhya Pradesh': [],
  'Maharashtra': [
    '',
    'Ahmednagar',
    'Akola',
    'Amravati',
    'Aurangabad',
    'Beed',
    'Bhandara',
    'Buldhana',
    'Chandrapur',
    'Dhule',
    'Gadchiroli',
    'Gondia',
    'Hingoli',
    'Jalgaon',
    'Jalna',
    'Kolhapur',
    'Latur',
    'Mumbai City',
    'Mumbai Suburban',
    'Nagpur',
    'Nanded',
    'Nandurbar',
    'Nashik',
    'Osmanabad',
    'Palghar',
    'Parbhani',
    'Pune',
    'Raigad',
    'Ratnagiri',
    'Sangli',
    'Satara',
    'Sindhudurg',
    'Solapur',
    'Thane',
    'Wardha',
    'Washim',
    'Yavatmal',
  ],
  'Manipur': [],
  'Meghalaya': [],
  'Mizoram': [],
  'Nagaland': [],
  'Odisha': [],
  'Punjab': [],
  'Rajasthan': [],
  'Sikkim': [],
  'Tamil Nadu': [],
  'Telangana': [
    '',
    'Adilabad',
    'Bhadradri Kothagudem',
    'Hyderabad',
    'Jagtial',
    'Jangaon',
    'Jayashankar Bhupalpally',
    'Jogulamba Gadwal',
    'Kamareddy',
    'Karimnagar',
    'Khammam',
    'Komaram Bheem',
    'Mahabubabad',
    'Mahabubnagar',
    'Mancherial',
    'Medak',
    'Medchal-Malkajgiri',
    'Mulugu',
    'Nagarkurnool',
    'Nalgonda',
    'Narayanpet',
    'Nirmal',
    'Nizamabad',
    'Peddapalli',
    'Rajanna Sircilla',
    'Ranga Reddy',
    'Sangareddy',
    'Siddipet',
    'Suryapet',
    'Vikarabad',
    'Wanaparthy',
    'Warangal Rural',
    'Warangal Urban',
    'Yadadri Bhuvanagiri',
  ],
  'Tripura': [],
  'Uttarakhand': [],
  'Uttar Pradesh': [],
  'West Bengal': [],
  'Andaman and Nicobar Islands': [],
  'Chandigarh': [],
  'Dadra and Nagar Haveli': [],
  'Daman and Diu': [],
  'Delhi': [],
  'Lakshadweep': [],
  'Puducherry': [],
};
